sprint-2/step-2
wwwjsx/react-burger pull request #3
Opened 2022-09-20 10:51 UTC by wwwjsx

1. перевел загрузки данных на redux
2. добавил react-dnd

2022-09-20 12:40 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодцы!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализовано переключение в навигации по ингредиентам;

### **Но есть несколько замечаний, которые нужно исправить:**

- По макеты ингредиенты в burgerConstructor, должны быть на всю ширину.

  ![image](https://user-images.githubusercontent.com/70164458/191259833-d4fc6398-e915-4702-b440-a738ebc138e8.png)


- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app.

- При скролле внутри компонента BurgerIngredients самый ближний к верхней левой границе заголовок контейнера должен
  становится активным;

- По чек-листу вы должны использовать расширители хранилища, мидлвар thunk и applyMiddleware при подключении хранилища.

- В некоторых компонентах, обработчики событий написаны в самом jsx. Лучше создать отдельную функцию для этого. Так мы сможем, если будет необходимо, мемоизировать функцию, а также это улучшит читабельность кода.

- Не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только,  если он открыт, используя для этого условный рендеринг

  ```
  {isOpen && (
      компонент открываемого попапа
  )}
  ``
  ```

### **Сделает код лучше:**

- Стоит вынести компоненты в отдельные папки, потому что со временем, их число будет только увеличиваться, и потом сложно будет искать нужный компонент. Рекомендую взять за правило, 1 папка - 1 компонент.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-20 12:40 UTC, ArslanMustafin commented on src/components/app/App.jsx
> +    }, [ingredientsError]);
**Надо исправить:** Т.к мы используем `redux`, то нам не нужно следить за состоянием переменных, редакс сам перерисует компонент, там где используется `useSelector`, если state измениться. Поэтому лучшим вариантом тут, будет, напрямую использовать `ingredientsFail` в качестве проверки.

2022-09-20 12:40 UTC, ArslanDev666 commented on src/components/constructor/BurgerConstructor.jsx
>              }
**Можно лучше:** Постарайтесь, не использовать вложенные if, если это возможно. Как вариант, можно попробовать подход "ранний возврат" https://habr.com/ru/post/348074/

2022-09-20 12:40 UTC, ArslanDev666 commented on src/components/constructor/BurgerConstructor.jsx
>              }
**Можно лучше:** Можно написать проще, используя тернарные оператор.
```js 
const text = `${constructorBun.name} ${type === 'top'? '(верх)' : '(низ)'}`
```

Аналогично можно упростить, ниже. И не забывайте, что в таком случае, переменная будет задаваться через `const`.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Conditional_Operator

2022-09-20 12:40 UTC, ArslanDev666 commented on src/components/constructor/BurgerConstructor.jsx
>      const renderBun = (type) => {
**Надо исправить:** Лучше обернуть в useMemo, тогда, переменная не будет лишний раз создаваться при ререндере.
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2022-09-20 12:40 UTC, ArslanDev666 commented on src/components/constructor/BurgerConstructor.jsx
>                          text={text}
**Можно лучше:** Можно написать просто isLocked, без значения. Это будет тоже самое что и isLocked={true}.

2022-09-20 12:40 UTC, ArslanDev666 commented on src/components/constructor/ElementWrapper.jsx
> +    const preventDefault = (e) => e.preventDefault();
**Можно лучше:** Лучше исправить название на `handleOnDrop`, в данном случае мы должны показать, где, и в качестве чего будет эта функция применяться. Т.к мы подписываемся на событие `onDrop`, то `handleOnDrop`.

2022-09-20 12:40 UTC, ArslanDev666 commented on src/components/constructor/BurgerConstructor.jsx
> +                            handleClose={(e) => handleClose(e, item)}
**Надо исправить:** Здесь и в похожихъ местах. Лучше написать вот так, т.к мы не используем `e`.
```js 
handleClose={() => handleClose(item)}
```

2022-09-20 12:40 UTC, ArslanDev666 commented on src/components/constructor/BurgerConstructor.jsx
> +                        onClose={() => setIsOrderModal(false)}
**Надо исправить:** Здесь и в похожих местах. Лучше создать отдельный обработчик событий для этого, например: `handleCloseModalOrder`.

2022-09-20 12:40 UTC, ArslanDev666 commented on src/services/actions/ingredients.js
> +            });
**Можно лучше**

Лучше вынести описание запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`.

2022-09-20 12:40 UTC, ArslanDev666 commented on src/services/reducers/ingredients.js
> +    const min = 2; // minimum 2 ingredients
**Надо исправить:** В коде не должно быть магических значений. 
Тут вам просто вынести за пределы функции это значение. А также использовать в названии `upper_case`.

"Магические" значения это - такие значения в коде, смысл которых понятен только написавшему их программисту. Например, иногда в интернет-магазинах цену товара автоматически умножают на 1.2, вместо того чтобы ввести понятную переменную для НДС. И без комментариев такие коэффициенты понять очень сложно.

2022-09-20 18:16 UTC, wwwjsx commented on src/components/constructor/BurgerConstructor.jsx
>      const renderBun = (type) => {
Я перевел эту функци на useMemo и получил ошибку: 

`Cannot update a component (`BurgerIngredients`) while rendering a different component (`BurgerConstructor`). To locate the bad setState() call inside `BurgerConstructor`, follow the stack trace as described in`

внутри этой функции используется dispatch  и оно причина этой ошибки. Как исправить это? Разные варианты пробовал.

2022-09-20 20:58 UTC, ArslanDev666 commented on src/components/constructor/BurgerConstructor.jsx
>      const renderBun = (type) => {
Ага, перепроверил, появляется ошибка, т.к это функция, видимо я не обратил внимание на параметры. 
В таком случае. это замечание можно пометить как:  
**Можно лучше:** Лучше перенести логику отображения в jsx. Примерно вот таким образом:

```js
{constructorBun ? (
  <div className={`${styles.element} ${isBunHover && styles.bunHover}`}>
    <div className={styles.elementIcon}></div>
    <ConstructorElement
        type="top"
        isLocked={true}
        text={`${constructorBun.name} (верх)`}
        price={constructorBun.price}
        thumbnail={constructorBun.image_mobile}
    />
</div>
) : (
  <div
    className={`${styles.noBuns} ${dragBuns && styles.dragActive} ${
      styles.noBunsTop
    } ml-8 mb-4 mr-5 text text_type_main-default`}
  >
    Выберите булки
  </div>
)}
```

2022-09-20 21:10 UTC, wwwjsx commented on src/components/constructor/BurgerConstructor.jsx
>      const renderBun = (type) => {
useEffect используется чтобы посчитать цены ингредиенты - то что показываешь что это делает ? Здесь как я буду посчитать цена ?

2022-09-21 08:43 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!
Все замечания были исправлены.

## Сделает код лучше

- В будущем, попробуйте использовать [redux-toolkit](https://redux-toolkit.js.org/).

2022-09-21 08:43 UTC, ArslanDev666 commented on src/components/ingredients/BurgerIngredients.jsx
>      };
**Можно лучше:** Если этого не запрещает задание, то можно использовать готовые решения, например - [react-intersection-observer](https://www.npmjs.com/package/react-intersection-observer).

2022-09-21 08:55 UTC, merged

2022-09-21 15:26 UTC, ArslanDev666 commented on src/components/constructor/BurgerConstructor.jsx
>      const renderBun = (type) => {
Видимо так выделилось, но я имелл виду, не useEffect, а функцию `renderBun`.