sprint-4/step-1
wwwjsx/react-burger pull request #5
Opened 2022-10-03 18:24 UTC by wwwjsx

перевел все файлы на TypeScript

2022-10-03 18:56 UTC, andryxxa93 requested changes
Отличная работа! Очень понравилось, что вы по-минимуму используете `any` и `as`. С точки зрения typescript всё очень грамотно, ошибок нет. 
Есть правда одно замечание не касающиеся typesctipt, но вызывающее баг - при логине выскакивает ошибка -  
<img width="562" alt="Снимок экрана 2022-10-03 в 21 37 02" src="https://user-images.githubusercontent.com/60173362/193656290-5f0f4375-67bf-41f8-b337-dd4c2af36ed6.png">.
Чтобы работа была принята это следует исправить. Так же обратите внимание на рекомендации как можно улучшить код в комментариях к pull request.

Удачных правок!

2022-10-03 18:56 UTC, andryxxa93 commented on src/components/ingredients/Ingredient.tsx
> +                { typeof item.count === 'number' && Number(item.count) > 0 &&
**Можно лучше**
Так как у вас указан тип для `count` = `number`. То необходимости проверять является ли он числом нет. Я понимаю, что вы хотите убедиться, что count !== undefined. Но это можно сделать лаконичнее -
```
{ item.count && <Counter count={item.count} size="default" />}
```

2022-10-03 18:56 UTC, andryxxa93 commented on src/components/pages/profile/ProfileForm.tsx
> +    const user = typeof auth.user === 'object' ? auth.user : {};
**Можно лучше**
Тут можно использовать nulish coalesing. Если auth.user будет undefined или null он выберет пустой объект. 
   ` const user = auth?.user ?? {};`. 
Так же можно оператор ИЛИ `||` использовать.
https://learn.javascript.ru/nullish-coalescing-operator

2022-10-03 18:56 UTC, andryxxa93 commented on src/utils/api/api.ts
> +const auth = (method: 'POST' | 'GET' | 'DELETE' | 'PUT' | 'PATCH', params: { token: string | null, body?: any }): object => {
**Можно лучше**
Вот такие длинные перечисления лучше выносить в отдельные типы.

2022-10-04 05:08 UTC, wwwjsx commented on src/components/ingredients/Ingredient.tsx
> +                { typeof item.count === 'number' && Number(item.count) > 0 &&
я так пробовал если кол-во товаров 0 то 0 появляется рядом блоком. По этому добавил typeof.

2022-10-04 06:20 UTC, andryxxa93 commented on src/components/ingredients/Ingredient.tsx
> +                { typeof item.count === 'number' && Number(item.count) > 0 &&
тогда можно вот так - !!item.count &&. Тогда тип точно станет булиновым и если это 0, то станет false

2022-10-04 06:20 UTC, andryxxa93 approved these changes
Ваша работа принята! Удачного продолжения обучения!

2022-10-04 06:37 UTC, merged